[package]
name = "bdo3"
version = "0.1.0"
authors = ["John S <john@john2143.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_fly_camera = "0.2.0"
bevy = "0.1.3"
