[package]
name = "bdo2"
version = "0.1.0"
authors = ["John2143"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "=1.0.1" #needed for rust-lang-nursery/failure#342

[dependencies.tokio]
version = "0.2.21"
features = ["full"]

[dependencies.amethyst]
version = "0.12.0"
features = ["vulkan"]
