[package]
name = "bdo2"
version = "0.1.0"
authors = ["John"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.4"
winit = "0.22.2"
futures = "0.3.5"
shaderc = "0.6.2"
bytemuck = "1.2.0"
failure = "0.1.8"
cgmath = "0.17.0"

[dependencies.tokio]
version = "0.2.21"
features = ["full"]

[dependencies.wgpu]
version = "0.5.0"
features = ["vulkan"]
