[package]
name = "bdo3"
version = "0.1.0"
authors = ["John S <john@john2143.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.1.3"
bevy_type_registry = "0.1.3"
bevy_core = "0.1.3"
bevy_transform = "0.1.3"
bevy_diagnostic = "0.1.3"
bevy_input = "0.1.3"
bevy_window = "0.1.3"
bevy_asset = "0.1.3"
bevy_scene = "0.1.3"
bevy_render = "0.1.3"
bevy_sprite = "0.1.3"
bevy_pbr = "0.1.3"
bevy_ui = "0.1.3"
bevy_text = "0.1.3"

bevy_audio = "0.1.3"
bevy_gltf = "0.1.3"
bevy_winit = "0.1.3"
bevy_wgpu = "0.1.3"

bevy_fly_camera = "0.2.0"
lazy_static = "1.4.0"
