name: ZipTest

on:
  push:
    branches: [ cicd_fix ]
  pull_request:
    branches: [ cicd_fix]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use nightly rustup
      run: 7z a assets.zip assets\
